### ISSUE TITLE
Is it possible to have multiple /test folders

### ISSUE THREAD

**Issue by Bazni** [AdrienAudouard/flutter-utils#2]
Hey,
Thank you for your work.

Can multiple paths be added to the test folder?
I use a mono repo with different packages, it would be cool to show my coverage for each package.

**Comment by AdrienAudouard** [comment]
Hey, 
Thanks for your feedback, yes I'm working on that, I'll let you know when it's available !

**Comment by AdrienAudouard** [comment]
Hey, 
I've updated the extension and it now support mono repo (version 1.4.0), you have nothing to do to make it works.
